apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
  namespace: web-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: web-storage
  hostPath:
    path: "/mnt/data"
