apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: web-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: web-storage
  resources:
    requests:
      storage: 500Mi
